// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: javascript_package.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "javascript_package.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {


}  // namespace


void protobuf_AssignDesc_javascript_5fpackage_2eproto() {
  protobuf_AddDesc_javascript_5fpackage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "javascript_package.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_javascript_5fpackage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_javascript_5fpackage_2eproto() {
}

void protobuf_AddDesc_javascript_5fpackage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030javascript_package.proto\032 google/proto"
    "buf/descriptor.proto::\n\022javascript_packa"
    "ge\022\034.google.protobuf.FileOptions\030\320\206\003 \001(\t", 120);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "javascript_package.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::FileOptions::default_instance(),
    50000, 9, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_javascript_5fpackage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_javascript_5fpackage_2eproto {
  StaticDescriptorInitializer_javascript_5fpackage_2eproto() {
    protobuf_AddDesc_javascript_5fpackage_2eproto();
  }
} static_descriptor_initializer_javascript_5fpackage_2eproto_;
const ::std::string javascript_package_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  javascript_package(kJavascriptPackageFieldNumber, javascript_package_default);

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
