run:
	java -jar plovr.jar serve plovr-config-dev.js

compile_pretty:
	java -jar plovr.jar build plovr-config-dev.js > main.js

compile:
	java -jar plovr.jar build plovr-config-prod.js > min/main.min.js
